#!/usr/bin/perl
# $Id: BkSource.pl,v 1.5 2007/12/05 02:16:31 lam Exp lam $
# https://q.lam1.us/Comments?Topic=Program;Name=BkSource.pl;Submit=View
use warnings;                                              # Enable all warnings
use strict;                             # Force me to use strict variable syntax
my $programName = '';$0 =~ m@.*/(.*)@ and $programName = $1; # path/$programName

my $cfDir = '/etc/Backup'; my $configFile = "$cfDir/$programName.conf";
open (CONFIG, $configFile)                                  # configuration file.
 or die "Run time error: $0\nConfiguration file: $configFile NOT opened!\n$!\n\n";

my $bkDir = ''; chop($bkDir = <CONFIG>);                # backup target directory
my $bkList = ''; chop($bkList = <CONFIG>);                          # backup list
close(CONFIG);
my $find = "find $bkList -name \'*,v\' -print0";              # find RCS archives
my $sed = 'sed -e \'s_/RCS/_/_g\' -e \'s_,v__g\'';  # find source by RCS archives

-d $bkDir              # Perform Backup only if target directory is found/mounted
 or die "Run time error: $0\nBackup target: $bkDir NOT found!\n$!\n\n";

my $tmpDir = '/var/tmp';              # Use local temporary then move files later

my $newDir = qx(date '+%y%m%d'); chop($newDir);                          # YYMMDD
chdir '/';            # Perform Backup so archives have relative path information

my $outPrefix = $programName; my $gen = 1;                 # Set prefix for files
while (-e "$bkDir/$newDir/$outPrefix.out"
    or -e "$tmpDir/$outPrefix.out") {       # If current generation level is used
    $gen++; $outPrefix = "$programName.$gen";   # Increment out prefix generation
}                                   
open(STDOUT, ">>$tmpDir/$outPrefix.out")              # Re-direct standard output
 or die "$0 error:\nCan't redirect stdout\n$!\n\n";
open(STDERR, ">>$tmpDir/$outPrefix.out.err")                   # and error output
 or die "$0 error:\nCan't redirect stderr\n$!\n\n";                    # to files

my $uname = qx(uname -n); chomp($uname);                              # Host name
my $sdate = qx(date '+%A, %B %-d, %Y @ %r');                 # System Date / Time

print "=========================================\n",                # Job started
    "$uname $outPrefix Job started $sdate\n";

print "Program: $0\nConfiguration file: $configFile\nConfiguration data:\n\n";
system("cat $configFile");                       # Report configuration file data
print "\n";

print "Checking source files ...\n\n";                             # Check source
system("$find | $sed | xargs -0 rcsdiff -U0");
print "\n"; system("date '+%A, %B %-d, %Y @ %r'"); print "\n";

$sdate = qx(date '+%A, %B %-d, %Y @ %r');                    # System Date / Time

print "Moving output files from $tmpDir to ";
chdir $bkDir; system("mkdir $newDir");
chdir $newDir; system('pwd');                                       # Move output

print "\n$uname $outPrefix Job ended $sdate";
print "=========================================\n";                # Almost done
system("mv /var/tmp/$outPrefix*out* .");
close(STDOUT); close(STDERR);                                 # That's all folks!
